version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - postgresenv
    volumes:
      - ./init_db_data:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    depends_on:
      - db
    restart: always
    ports:
      - "8888:80"
    env_file:
      - pgadminenv
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: