version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .postgresenv
    volumes:
      - ./init_db_data:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    depends_on:
      - postgres
    restart: always
    ports:
      - "8888:80"
    env_file:
      - pgadminenv
    volumes:
      - pgadmin-data:/var/lib/pgadmin
